name: Deploy on new release

on:
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Tofu to Nuget

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
    - name: Build pakcage
      run: dotnet pack -o out --configuration Release /p:Version=${VERSION}
      env:
        VERSION: ${{ github.event.release.tag_name }}
    - name: Deploy package
      run: dotnet nuget push out/TofuProject.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json -k ${NUGET_TOKEN}
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_API_KEY }}