name: .NET Core Test and Publish

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
    - name: Format code
      run: dotnet format Tofu.sln && ls && cat Tofu.sln
    - name: Build
      run: dotnet run build src/Tofu/Tofu.csproj --configuration Release
  
  test:
    runs-on: ubuntu-latest
    name: Test
    needs: build

    steps:
    - name: Skip for now
      run: echo "skipping"

  publish:
    runs-on: ubuntu-latest
    name: Publish Tofu package
    needs: test

    steps:
    - name: Publish to NuGet
      run: echo "Publishing later, one the build works"

 

