name: .NET Core Test and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
    - name: Format code
      run: dotnet format Tofu.sln
    - name: Build
      run: dotnet build Tofu.sln --configuration Release
  
  test:
    runs-on: ubuntu-latest
    name: Test
    needs: build

    steps:
    - name: No tests right now
      run: echo "skipping"

  publish:
    runs-on: ubuntu-latest
    name: Publish Tofu package
    needs: test

    steps:
    - name: Publish to NuGet
      run: dotnet nuget push src/Tofu/bin/Debug/*.nupkg --source https://api.nuget.org/v3/index.json -k ${NUGET_TOKEN}
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_API_KEY }}